baseURL = "https://www.wirfuerapolda.de/"
languageCode = "de-DE"
title = "Wir Für Apolda - Kein Ort für Nazis!"
theme = "highlights"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Wir Für Apolda - Kein Ort für Nazis!"
  description = "Alle Informationen zur Organisation der Veranstaltung: Wir Für Apolda/Magdala - Kein Ort für Nazis! Magdala, 5. + 6. Oktober"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    type = "hero"
    title = "#wirfürapolda - Kein Ort für Nazis!"
    description = "Alle Informationen zur Organisation der Veranstaltung: #wirfürapolda - Kein Ort für Nazis! 5. + 6. Oktober"
    buttontext = "Aktuelles"

  # Termine
  [[params.block]]
    id = "news"
    type = "text"
    title = "Aktuelles"
    description = """
**3. Oktober, 12:00 Uhr - Kreide-Mal-Aktion der Kirche**<br />
*Marktplatz Apolda, Straßenmalkreide ist genug vorhanden*

**5. Oktober, ab 14:00 Uhr - Protest-Programm**<br />
*Magdala, [Shuttle-Service](./files/Flyer-Shuttle-Magdala.pdf) ab Weimar und Apolda*<br />
[Programm-Flyer herunterladen](./files/Flyer-Programm-Magdala.pdf)

**6. Oktober, ab 10:00 Uhr - Protest-Programm**<br />
*Magdala, [Shuttle-Service](./files/Flyer-Shuttle-Magdala.pdf) ab Weimar und Apolda*<br />
[Programm-Flyer herunterladen](./files/Flyer-Programm-Magdala.pdf)


**AUSSCHLUSSKLAUSEL**
Entsprechend § 6 Absatz 1 Versammlungsgesetz Ich sind Personen, die rechtsextremen Parteien oder Organisationen angehören, der rechtsextremen Szene zuzuordnen sind oder bereits in der Vergangenheit durch rassistische, nationalistische, antisemitische oder sonstige menschenverachtende Äußerungen in Erscheinung getreten sind, von der Veranstaltung ausgeschlossen.
"""
    buttontext = "next"
    picture = "wirfuermagdala.png"

  [[params.block]]
    id = "program"
    type = "text"
    title = "Programm"
    description = """
**5. + 6. Oktober**<br />
[Programm-Flyer herunterladen](./files/Flyer-Programm-Magdala.pdf)<br/>

Der Protest findet in Magdala statt.
Wir haben einen [Shuttle-Service](./files/Flyer-Shuttle-Magdala.pdf) eingerichtet.

Teilnehmer aus Jena können mit dem Zug nach Weimar reisen und dann den Shuttle-Service nach Magdala nutzen.

<object data="files/Flyer-Programm-Magdala.pdf" type="application/pdf" style="width:100%;height:600px">
  <a href="files/Flyer-Programm-Magdala.pdf">Programm Flyer herunterladen</a>
</object>

[Programm-Flyer herunterladen](./files/Flyer-Programm-Magdala.pdf)<br/>
[Abfahrzeiten Shuttle-Service](./files/Flyer-Shuttle-Magdala.pdf)
"""
    buttontext = "next"

  # Apolda
  [[params.block]]
    id = "apolda"
    type = "text"
    title = "Offener Brief an den Freistaat Thüringen"
    description = """
Mit einem offenen Brief wenden sich Bürgermeister Rüdiger Eisenbrand und die Apoldaer Stadtratsfraktionen an den Freistaat Thüringen und die demokratischen Fraktionen im Thüringer Landtag.

In dem Brief bitten die Beteiligten um Unterstützung der Kreisstadt, das für den 5. und 6 Oktober 2018 geplante Rechtsrockkonzert zu unterbinden und der Zivilgesellschaft sowie den Bürgerinnen und Bürgern zu helfen, die Grundrechte und die Gesellschaftsordnung zu verteidigen.

Seit Bekanntwerden des Ereignisses in unserer Stadt sind große Teile der Bevölkerung verängstigt und in großer Sorge – um ihr Eigentum, um ihre Gesundheit, aber auch um den guten Ruf ihrer Heimat.

<object data="files/Offener-Brief-Buergermeister-Stadtrat.pdf" type="application/pdf" style="width:100%;height:600px">
  <a href="files/Offener-Brief-Buergermeister-Stadtrat.pdf">Offener Brief von Bürgermeister und Stadtrat herunterladen</a>
</object>

[Offener Brief von Bürgermeister und Stadtrat herunterladen](./files/Offener-Brief-Buergermeister-Stadtrat.pdf)
"""
    buttontext = "next"

  # Wir
  [[params.block]]
    id = "about"
    type = "text"
    title = "Wir sind viele!"
    description = """
Hinter dem **Wir** steht ein breites Bündnis aus Privatpersonen, Institutionen, Vereinen, Firmen und demokratischen Parteien und Fraktionen des Apoldaer Stadtrates.

In mehreren Gruppen teilen wir uns rein in die Vorbereitung und Organisation des friedlichen Protests gegen die Rechte Großkundgebung auf unserem Marktplatz in Apolda. Jeder kann sich uns gern anschließen.

<object data="files/Infoflyer-Wir-fuer-Apolda.pdf" type="application/pdf" style="width:100%;height:600px">
  <a href="files/Infoflyer-Wir-fuer-Apolda.pdf">Unseren Infoflyer herunterladen</a>
</object>

[Infoflyer herunterladen](./files/Infoflyer-Wir-fuer-Apolda.pdf)
"""
    buttontext = "next"

  # Orientierung
  [[params.block]]
    id = "programm"
    type = "text"
    title = "Orientierung"
    description = """
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2509.5417950085402!2d11.516711316339617!3d51.02461335370685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a41de4a3a79975%3A0xd825931365509ff6!2sMehrgenerationenhaus+%22Geschwister+Scholl%22+Apolda!5e0!3m2!1sde!2sde!4v1536315336223" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>"""
    buttontext = "next"

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is storead at static/images/
#    picture = "pic04.jpg"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/wirfuerapolda/"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "mailto:wir@wirfuerapolda.da"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© 2018 [ARRANCA e.V.](http://www.arranca-kirchheim.de/)"

      [[params.footer.copyright.notice]]
        text = "[Datenschutz & Impressum](http://www.arranca-kirchheim.de/impressum.htm)"
